# Site settings
title: LambdaSpace
email: info@lambdaspace.gr
description: >
 Join a vibrant community of hackers
baseurl: "https://vasal19.github.com/githubpages-boilerplate"
url: "https://vasal19.github.com/githubpages-boilerplate"
twitter_username: lambdaspace
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
